all:
	cat Makefile


install:
	# type npm
	# npm install -g @anthropic-ai/claude-code
	# bun install -g @anthropic-ai/claude-code
	curl -fsSL https://claude.ai/install.sh | bash
	echo "run: claude"
	echo "then: /login"

update:
	claude update
	# npm update -g @anthropic-ai/claude-code
	# bun update -g @anthropic-ai/claude-code
