# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transcript_participant import TranscriptParticipant  # noqa: E501
from swagger_client.rest import ApiException


class TestTranscriptParticipant(unittest.TestCase):
    """TranscriptParticipant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscriptParticipant(self):
        """Test TranscriptParticipant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transcript_participant.TranscriptParticipant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
