# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dividends2_info import Dividends2Info  # noqa: E501
from swagger_client.rest import ApiException


class TestDividends2Info(unittest.TestCase):
    """Dividends2Info unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDividends2Info(self):
        """Test Dividends2Info"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dividends2_info.Dividends2Info()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
