# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.revenue_estimates_info import RevenueEstimatesInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestRevenueEstimatesInfo(unittest.TestCase):
    """RevenueEstimatesInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRevenueEstimatesInfo(self):
        """Test RevenueEstimatesInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.revenue_estimates_info.RevenueEstimatesInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
