# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.news_sentiment import NewsSentiment  # noqa: E501
from swagger_client.rest import ApiException


class TestNewsSentiment(unittest.TestCase):
    """NewsSentiment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewsSentiment(self):
        """Test NewsSentiment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.news_sentiment.NewsSentiment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
