# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.indices_historical_constituents import IndicesHistoricalConstituents  # noqa: E501
from swagger_client.rest import ApiException


class TestIndicesHistoricalConstituents(unittest.TestCase):
    """IndicesHistoricalConstituents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndicesHistoricalConstituents(self):
        """Test IndicesHistoricalConstituents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.indices_historical_constituents.IndicesHistoricalConstituents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
