all:
	cat Makefile

install:
	# sudo apt install -y direnv
	curl -sfL https://direnv.net/install.sh | bash

# # then do stuff like this
# direnv allow .
# direnv reload
#
# # do not forgot .bashrc
# eval "$(direnv hook bash)"
