all:
	cat Makefile

view:
	systemd-resolve --status

test:
	dig +trace www.stackoverflow.com

clear:
	sudo /etc/init.d/networking restart
	# uname osx
	# sudo killall -HUP mDNSResponder

ping:
	ping dsldevice.lan
