# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from finnhub_swagger_api.configuration import Configuration


class AggregateIndicators(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'technical_analysis': 'TechnicalAnalysis',
        'trend': 'Trend'
    }

    attribute_map = {
        'technical_analysis': 'technicalAnalysis',
        'trend': 'trend'
    }

    def __init__(self, technical_analysis=None, trend=None, _configuration=None):  # noqa: E501
        """AggregateIndicators - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._technical_analysis = None
        self._trend = None
        self.discriminator = None

        if technical_analysis is not None:
            self.technical_analysis = technical_analysis
        if trend is not None:
            self.trend = trend

    @property
    def technical_analysis(self):
        """Gets the technical_analysis of this AggregateIndicators.  # noqa: E501

        Number of indicator signals strong buy, buy, neutral, sell, strong sell signals.  # noqa: E501

        :return: The technical_analysis of this AggregateIndicators.  # noqa: E501
        :rtype: TechnicalAnalysis
        """
        return self._technical_analysis

    @technical_analysis.setter
    def technical_analysis(self, technical_analysis):
        """Sets the technical_analysis of this AggregateIndicators.

        Number of indicator signals strong buy, buy, neutral, sell, strong sell signals.  # noqa: E501

        :param technical_analysis: The technical_analysis of this AggregateIndicators.  # noqa: E501
        :type: TechnicalAnalysis
        """

        self._technical_analysis = technical_analysis

    @property
    def trend(self):
        """Gets the trend of this AggregateIndicators.  # noqa: E501

        Whether the market is trending.  # noqa: E501

        :return: The trend of this AggregateIndicators.  # noqa: E501
        :rtype: Trend
        """
        return self._trend

    @trend.setter
    def trend(self, trend):
        """Sets the trend of this AggregateIndicators.

        Whether the market is trending.  # noqa: E501

        :param trend: The trend of this AggregateIndicators.  # noqa: E501
        :type: Trend
        """

        self._trend = trend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AggregateIndicators, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AggregateIndicators):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AggregateIndicators):
            return True

        return self.to_dict() != other.to_dict()
