# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from finnhub_swagger_api.configuration import Configuration


class IPOCalendar(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ipo_calendar': 'list[IPOEvent]'
    }

    attribute_map = {
        'ipo_calendar': 'ipoCalendar'
    }

    def __init__(self, ipo_calendar=None, _configuration=None):  # noqa: E501
        """IPOCalendar - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ipo_calendar = None
        self.discriminator = None

        if ipo_calendar is not None:
            self.ipo_calendar = ipo_calendar

    @property
    def ipo_calendar(self):
        """Gets the ipo_calendar of this IPOCalendar.  # noqa: E501

        Array of IPO events.  # noqa: E501

        :return: The ipo_calendar of this IPOCalendar.  # noqa: E501
        :rtype: list[IPOEvent]
        """
        return self._ipo_calendar

    @ipo_calendar.setter
    def ipo_calendar(self, ipo_calendar):
        """Sets the ipo_calendar of this IPOCalendar.

        Array of IPO events.  # noqa: E501

        :param ipo_calendar: The ipo_calendar of this IPOCalendar.  # noqa: E501
        :type: list[IPOEvent]
        """

        self._ipo_calendar = ipo_calendar

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IPOCalendar, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPOCalendar):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IPOCalendar):
            return True

        return self.to_dict() != other.to_dict()
