# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from finnhub_swagger_api.configuration import Configuration


class SimilarityIndexInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cik': 'str',
        'item1': 'float',
        'item1a': 'float',
        'item2': 'float',
        'item7': 'float',
        'item7a': 'float',
        'access_number': 'str',
        'form': 'str',
        'filed_date': 'str',
        'accepted_date': 'str',
        'report_url': 'str',
        'filing_url': 'str'
    }

    attribute_map = {
        'cik': 'cik',
        'item1': 'item1',
        'item1a': 'item1a',
        'item2': 'item2',
        'item7': 'item7',
        'item7a': 'item7a',
        'access_number': 'accessNumber',
        'form': 'form',
        'filed_date': 'filedDate',
        'accepted_date': 'acceptedDate',
        'report_url': 'reportUrl',
        'filing_url': 'filingUrl'
    }

    def __init__(self, cik=None, item1=None, item1a=None, item2=None, item7=None, item7a=None, access_number=None, form=None, filed_date=None, accepted_date=None, report_url=None, filing_url=None, _configuration=None):  # noqa: E501
        """SimilarityIndexInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cik = None
        self._item1 = None
        self._item1a = None
        self._item2 = None
        self._item7 = None
        self._item7a = None
        self._access_number = None
        self._form = None
        self._filed_date = None
        self._accepted_date = None
        self._report_url = None
        self._filing_url = None
        self.discriminator = None

        if cik is not None:
            self.cik = cik
        if item1 is not None:
            self.item1 = item1
        if item1a is not None:
            self.item1a = item1a
        if item2 is not None:
            self.item2 = item2
        if item7 is not None:
            self.item7 = item7
        if item7a is not None:
            self.item7a = item7a
        if access_number is not None:
            self.access_number = access_number
        if form is not None:
            self.form = form
        if filed_date is not None:
            self.filed_date = filed_date
        if accepted_date is not None:
            self.accepted_date = accepted_date
        if report_url is not None:
            self.report_url = report_url
        if filing_url is not None:
            self.filing_url = filing_url

    @property
    def cik(self):
        """Gets the cik of this SimilarityIndexInfo.  # noqa: E501

        CIK.  # noqa: E501

        :return: The cik of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._cik

    @cik.setter
    def cik(self, cik):
        """Sets the cik of this SimilarityIndexInfo.

        CIK.  # noqa: E501

        :param cik: The cik of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._cik = cik

    @property
    def item1(self):
        """Gets the item1 of this SimilarityIndexInfo.  # noqa: E501

        Cosine similarity of Item 1 (Business). This number is only available for Annual reports.  # noqa: E501

        :return: The item1 of this SimilarityIndexInfo.  # noqa: E501
        :rtype: float
        """
        return self._item1

    @item1.setter
    def item1(self, item1):
        """Sets the item1 of this SimilarityIndexInfo.

        Cosine similarity of Item 1 (Business). This number is only available for Annual reports.  # noqa: E501

        :param item1: The item1 of this SimilarityIndexInfo.  # noqa: E501
        :type: float
        """

        self._item1 = item1

    @property
    def item1a(self):
        """Gets the item1a of this SimilarityIndexInfo.  # noqa: E501

        Cosine similarity of Item 1A (Risk Factors). This number is available for both Annual and Quarterly reports.  # noqa: E501

        :return: The item1a of this SimilarityIndexInfo.  # noqa: E501
        :rtype: float
        """
        return self._item1a

    @item1a.setter
    def item1a(self, item1a):
        """Sets the item1a of this SimilarityIndexInfo.

        Cosine similarity of Item 1A (Risk Factors). This number is available for both Annual and Quarterly reports.  # noqa: E501

        :param item1a: The item1a of this SimilarityIndexInfo.  # noqa: E501
        :type: float
        """

        self._item1a = item1a

    @property
    def item2(self):
        """Gets the item2 of this SimilarityIndexInfo.  # noqa: E501

        Cosine similarity of Item 2 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Quarterly reports.  # noqa: E501

        :return: The item2 of this SimilarityIndexInfo.  # noqa: E501
        :rtype: float
        """
        return self._item2

    @item2.setter
    def item2(self, item2):
        """Sets the item2 of this SimilarityIndexInfo.

        Cosine similarity of Item 2 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Quarterly reports.  # noqa: E501

        :param item2: The item2 of this SimilarityIndexInfo.  # noqa: E501
        :type: float
        """

        self._item2 = item2

    @property
    def item7(self):
        """Gets the item7 of this SimilarityIndexInfo.  # noqa: E501

        Cosine similarity of Item 7 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Annual reports.  # noqa: E501

        :return: The item7 of this SimilarityIndexInfo.  # noqa: E501
        :rtype: float
        """
        return self._item7

    @item7.setter
    def item7(self, item7):
        """Sets the item7 of this SimilarityIndexInfo.

        Cosine similarity of Item 7 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Annual reports.  # noqa: E501

        :param item7: The item7 of this SimilarityIndexInfo.  # noqa: E501
        :type: float
        """

        self._item7 = item7

    @property
    def item7a(self):
        """Gets the item7a of this SimilarityIndexInfo.  # noqa: E501

        Cosine similarity of Item 7A (Quantitative and Qualitative Disclosures About Market Risk). This number is only available for Annual reports.  # noqa: E501

        :return: The item7a of this SimilarityIndexInfo.  # noqa: E501
        :rtype: float
        """
        return self._item7a

    @item7a.setter
    def item7a(self, item7a):
        """Sets the item7a of this SimilarityIndexInfo.

        Cosine similarity of Item 7A (Quantitative and Qualitative Disclosures About Market Risk). This number is only available for Annual reports.  # noqa: E501

        :param item7a: The item7a of this SimilarityIndexInfo.  # noqa: E501
        :type: float
        """

        self._item7a = item7a

    @property
    def access_number(self):
        """Gets the access_number of this SimilarityIndexInfo.  # noqa: E501

        Access number.  # noqa: E501

        :return: The access_number of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._access_number

    @access_number.setter
    def access_number(self, access_number):
        """Sets the access_number of this SimilarityIndexInfo.

        Access number.  # noqa: E501

        :param access_number: The access_number of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._access_number = access_number

    @property
    def form(self):
        """Gets the form of this SimilarityIndexInfo.  # noqa: E501

        Form type.  # noqa: E501

        :return: The form of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._form

    @form.setter
    def form(self, form):
        """Sets the form of this SimilarityIndexInfo.

        Form type.  # noqa: E501

        :param form: The form of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._form = form

    @property
    def filed_date(self):
        """Gets the filed_date of this SimilarityIndexInfo.  # noqa: E501

        Filed date <code>%Y-%m-%d %H:%M:%S</code>.  # noqa: E501

        :return: The filed_date of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._filed_date

    @filed_date.setter
    def filed_date(self, filed_date):
        """Sets the filed_date of this SimilarityIndexInfo.

        Filed date <code>%Y-%m-%d %H:%M:%S</code>.  # noqa: E501

        :param filed_date: The filed_date of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._filed_date = filed_date

    @property
    def accepted_date(self):
        """Gets the accepted_date of this SimilarityIndexInfo.  # noqa: E501

        Accepted date <code>%Y-%m-%d %H:%M:%S</code>.  # noqa: E501

        :return: The accepted_date of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._accepted_date

    @accepted_date.setter
    def accepted_date(self, accepted_date):
        """Sets the accepted_date of this SimilarityIndexInfo.

        Accepted date <code>%Y-%m-%d %H:%M:%S</code>.  # noqa: E501

        :param accepted_date: The accepted_date of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._accepted_date = accepted_date

    @property
    def report_url(self):
        """Gets the report_url of this SimilarityIndexInfo.  # noqa: E501

        Report's URL.  # noqa: E501

        :return: The report_url of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._report_url

    @report_url.setter
    def report_url(self, report_url):
        """Sets the report_url of this SimilarityIndexInfo.

        Report's URL.  # noqa: E501

        :param report_url: The report_url of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._report_url = report_url

    @property
    def filing_url(self):
        """Gets the filing_url of this SimilarityIndexInfo.  # noqa: E501

        Filing's URL.  # noqa: E501

        :return: The filing_url of this SimilarityIndexInfo.  # noqa: E501
        :rtype: str
        """
        return self._filing_url

    @filing_url.setter
    def filing_url(self, filing_url):
        """Sets the filing_url of this SimilarityIndexInfo.

        Filing's URL.  # noqa: E501

        :param filing_url: The filing_url of this SimilarityIndexInfo.  # noqa: E501
        :type: str
        """

        self._filing_url = filing_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimilarityIndexInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimilarityIndexInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SimilarityIndexInfo):
            return True

        return self.to_dict() != other.to_dict()
