# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from finnhub_swagger_api.configuration import Configuration


class StockSymbol(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'display_symbol': 'str',
        'symbol': 'str',
        'type': 'str',
        'mic': 'str',
        'figi': 'str',
        'currency': 'str'
    }

    attribute_map = {
        'description': 'description',
        'display_symbol': 'displaySymbol',
        'symbol': 'symbol',
        'type': 'type',
        'mic': 'mic',
        'figi': 'figi',
        'currency': 'currency'
    }

    def __init__(self, description=None, display_symbol=None, symbol=None, type=None, mic=None, figi=None, currency=None, _configuration=None):  # noqa: E501
        """StockSymbol - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._display_symbol = None
        self._symbol = None
        self._type = None
        self._mic = None
        self._figi = None
        self._currency = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if display_symbol is not None:
            self.display_symbol = display_symbol
        if symbol is not None:
            self.symbol = symbol
        if type is not None:
            self.type = type
        if mic is not None:
            self.mic = mic
        if figi is not None:
            self.figi = figi
        if currency is not None:
            self.currency = currency

    @property
    def description(self):
        """Gets the description of this StockSymbol.  # noqa: E501

        Symbol description  # noqa: E501

        :return: The description of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StockSymbol.

        Symbol description  # noqa: E501

        :param description: The description of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def display_symbol(self):
        """Gets the display_symbol of this StockSymbol.  # noqa: E501

        Display symbol name.  # noqa: E501

        :return: The display_symbol of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._display_symbol

    @display_symbol.setter
    def display_symbol(self, display_symbol):
        """Sets the display_symbol of this StockSymbol.

        Display symbol name.  # noqa: E501

        :param display_symbol: The display_symbol of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._display_symbol = display_symbol

    @property
    def symbol(self):
        """Gets the symbol of this StockSymbol.  # noqa: E501

        Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.  # noqa: E501

        :return: The symbol of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this StockSymbol.

        Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.  # noqa: E501

        :param symbol: The symbol of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def type(self):
        """Gets the type of this StockSymbol.  # noqa: E501

        Security type.  # noqa: E501

        :return: The type of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StockSymbol.

        Security type.  # noqa: E501

        :param type: The type of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def mic(self):
        """Gets the mic of this StockSymbol.  # noqa: E501

        Primary exchange's MIC.  # noqa: E501

        :return: The mic of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._mic

    @mic.setter
    def mic(self, mic):
        """Sets the mic of this StockSymbol.

        Primary exchange's MIC.  # noqa: E501

        :param mic: The mic of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._mic = mic

    @property
    def figi(self):
        """Gets the figi of this StockSymbol.  # noqa: E501

        FIGI identifier.  # noqa: E501

        :return: The figi of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._figi

    @figi.setter
    def figi(self, figi):
        """Sets the figi of this StockSymbol.

        FIGI identifier.  # noqa: E501

        :param figi: The figi of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._figi = figi

    @property
    def currency(self):
        """Gets the currency of this StockSymbol.  # noqa: E501

        Price's currency. This might be different from the reporting currency of fundamental data.  # noqa: E501

        :return: The currency of this StockSymbol.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this StockSymbol.

        Price's currency. This might be different from the reporting currency of fundamental data.  # noqa: E501

        :param currency: The currency of this StockSymbol.  # noqa: E501
        :type: str
        """

        self._currency = currency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StockSymbol, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StockSymbol):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StockSymbol):
            return True

        return self.to_dict() != other.to_dict()
