# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from finnhub_swagger_api.configuration import Configuration


class TranscriptParticipant(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'role': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'role': 'role'
    }

    def __init__(self, name=None, description=None, role=None, _configuration=None):  # noqa: E501
        """TranscriptParticipant - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._description = None
        self._role = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if role is not None:
            self.role = role

    @property
    def name(self):
        """Gets the name of this TranscriptParticipant.  # noqa: E501

        Participant's name  # noqa: E501

        :return: The name of this TranscriptParticipant.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TranscriptParticipant.

        Participant's name  # noqa: E501

        :param name: The name of this TranscriptParticipant.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this TranscriptParticipant.  # noqa: E501

        Participant's description  # noqa: E501

        :return: The description of this TranscriptParticipant.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TranscriptParticipant.

        Participant's description  # noqa: E501

        :param description: The description of this TranscriptParticipant.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def role(self):
        """Gets the role of this TranscriptParticipant.  # noqa: E501

        Whether the speak is a company's executive or an analyst  # noqa: E501

        :return: The role of this TranscriptParticipant.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this TranscriptParticipant.

        Whether the speak is a company's executive or an analyst  # noqa: E501

        :param role: The role of this TranscriptParticipant.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranscriptParticipant, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranscriptParticipant):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranscriptParticipant):
            return True

        return self.to_dict() != other.to_dict()
