# NOTE: as of 2025-12 requires pay-as-you go sub to x.ai not flat fee from grok.com etc

all:
	cat Makefile

install:
	# bun install -g @vibe-kit/grok-cli
	curl -fsSL https://x.ai/cli/install.sh | bash


update: install
	# bun install -g @vibe-kit/grok-cli@latest
