# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class BreakdownItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_number': 'str',
        'breakdown': 'BreakdownItemMap'
    }

    attribute_map = {
        'access_number': 'accessNumber',
        'breakdown': 'breakdown'
    }

    def __init__(self, access_number=None, breakdown=None, _configuration=None):  # noqa: E501
        """BreakdownItem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._access_number = None
        self._breakdown = None
        self.discriminator = None

        if access_number is not None:
            self.access_number = access_number
        if breakdown is not None:
            self.breakdown = breakdown

    @property
    def access_number(self):
        """Gets the access_number of this BreakdownItem.  # noqa: E501

        Access number of the report from which the data is sourced.  # noqa: E501

        :return: The access_number of this BreakdownItem.  # noqa: E501
        :rtype: str
        """
        return self._access_number

    @access_number.setter
    def access_number(self, access_number):
        """Sets the access_number of this BreakdownItem.

        Access number of the report from which the data is sourced.  # noqa: E501

        :param access_number: The access_number of this BreakdownItem.  # noqa: E501
        :type: str
        """

        self._access_number = access_number

    @property
    def breakdown(self):
        """Gets the breakdown of this BreakdownItem.  # noqa: E501

        Revenue breakdown.  # noqa: E501

        :return: The breakdown of this BreakdownItem.  # noqa: E501
        :rtype: BreakdownItemMap
        """
        return self._breakdown

    @breakdown.setter
    def breakdown(self, breakdown):
        """Sets the breakdown of this BreakdownItem.

        Revenue breakdown.  # noqa: E501

        :param breakdown: The breakdown of this BreakdownItem.  # noqa: E501
        :type: BreakdownItemMap
        """

        self._breakdown = breakdown

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BreakdownItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BreakdownItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BreakdownItem):
            return True

        return self.to_dict() != other.to_dict()
