# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Dividends2Info(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ex_date': 'date',
        'amount': 'float'
    }

    attribute_map = {
        'ex_date': 'exDate',
        'amount': 'amount'
    }

    def __init__(self, ex_date=None, amount=None, _configuration=None):  # noqa: E501
        """Dividends2Info - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ex_date = None
        self._amount = None
        self.discriminator = None

        if ex_date is not None:
            self.ex_date = ex_date
        if amount is not None:
            self.amount = amount

    @property
    def ex_date(self):
        """Gets the ex_date of this Dividends2Info.  # noqa: E501

        Ex-Dividend date.  # noqa: E501

        :return: The ex_date of this Dividends2Info.  # noqa: E501
        :rtype: date
        """
        return self._ex_date

    @ex_date.setter
    def ex_date(self, ex_date):
        """Sets the ex_date of this Dividends2Info.

        Ex-Dividend date.  # noqa: E501

        :param ex_date: The ex_date of this Dividends2Info.  # noqa: E501
        :type: date
        """

        self._ex_date = ex_date

    @property
    def amount(self):
        """Gets the amount of this Dividends2Info.  # noqa: E501

        Amount in local currency.  # noqa: E501

        :return: The amount of this Dividends2Info.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Dividends2Info.

        Amount in local currency.  # noqa: E501

        :param amount: The amount of this Dividends2Info.  # noqa: E501
        :type: float
        """

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Dividends2Info, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dividends2Info):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Dividends2Info):
            return True

        return self.to_dict() != other.to_dict()
