# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Trend(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adx': 'float',
        'trending': 'bool'
    }

    attribute_map = {
        'adx': 'adx',
        'trending': 'trending'
    }

    def __init__(self, adx=None, trending=None, _configuration=None):  # noqa: E501
        """Trend - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._adx = None
        self._trending = None
        self.discriminator = None

        if adx is not None:
            self.adx = adx
        if trending is not None:
            self.trending = trending

    @property
    def adx(self):
        """Gets the adx of this Trend.  # noqa: E501

        ADX reading  # noqa: E501

        :return: The adx of this Trend.  # noqa: E501
        :rtype: float
        """
        return self._adx

    @adx.setter
    def adx(self, adx):
        """Sets the adx of this Trend.

        ADX reading  # noqa: E501

        :param adx: The adx of this Trend.  # noqa: E501
        :type: float
        """

        self._adx = adx

    @property
    def trending(self):
        """Gets the trending of this Trend.  # noqa: E501

        Whether market is trending or going sideway  # noqa: E501

        :return: The trending of this Trend.  # noqa: E501
        :rtype: bool
        """
        return self._trending

    @trending.setter
    def trending(self, trending):
        """Sets the trending of this Trend.

        Whether market is trending or going sideway  # noqa: E501

        :param trending: The trending of this Trend.  # noqa: E501
        :type: bool
        """

        self._trending = trending

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Trend, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Trend):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Trend):
            return True

        return self.to_dict() != other.to_dict()
