# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finnhub_swagger_api
from finnhub_swagger_api.models.economic_event import EconomicEvent  # noqa: E501
from finnhub_swagger_api.rest import ApiException


class TestEconomicEvent(unittest.TestCase):
    """EconomicEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEconomicEvent(self):
        """Test EconomicEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finnhub_swagger_api.models.economic_event.EconomicEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
