# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finnhub_swagger_api
from finnhub_swagger_api.models.symbol_lookup_info import SymbolLookupInfo  # noqa: E501
from finnhub_swagger_api.rest import ApiException


class TestSymbolLookupInfo(unittest.TestCase):
    """SymbolLookupInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSymbolLookupInfo(self):
        """Test SymbolLookupInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finnhub_swagger_api.models.symbol_lookup_info.SymbolLookupInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
