# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import finnhub_swagger_api
from finnhub_swagger_api.models.mutual_fund_holdings_data import MutualFundHoldingsData  # noqa: E501
from finnhub_swagger_api.rest import ApiException


class TestMutualFundHoldingsData(unittest.TestCase):
    """MutualFundHoldingsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMutualFundHoldingsData(self):
        """Test MutualFundHoldingsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = finnhub_swagger_api.models.mutual_fund_holdings_data.MutualFundHoldingsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
