all:
	cat Makefile

install:
	# Download the latest stable .deb (amd64 / x86_64 – most common)
	wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.8.27/quarto-1.8.27-linux-amd64.deb

	# Install it (needs sudo)
	sudo apt install ./quarto-1.8.27-linux-amd64.deb
