start:
	microk8s start

stop:
	microk8s stop

status:
	microk8s status --wait-ready

enable:
	microk8s enable dashboard dns registry istio

ns:
	microk8s kubectl get all --all-namespaces

dash:
	microk8s dashboard-proxy


