FROM ubuntu:latest

# https://www.godaddy.com/garage/how-to-install-postgresql-on-ubuntu-14-04/

RUN apt-get install postgresql postgresql-contrib

# RUN update-rc.d postgresql enable
RUN service postgresql start
