FROM ubuntu:latest


# https://www.godaddy.com/garage/how-to-install-postgresql-on-ubuntu-14-04/

RUN apt-get update
RUN apt-get install -y postgresql postgresql-contrib
# echo PATH=$PATH:/usr/lib/postgresql/10/bin

# RUN update-rc.d postgresql enable
# RUN service postgresql start
