FROM ubuntu:latest

# https://www.godaddy.com/garage/how-to-install-postgresql-on-ubuntu-14-04/

RUN apt-get install postgresql postgresql-contrib

# update-rc.d postgresql enable
# service postgresql start
