swagger: "2.0"
info:
  version: "1.0.0"
  title: "Search API"
  description: "Miscellaneous search services"
  contact:
    name: "You name here"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
    - "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /search/item_to_items:
    get:
      description: "returns a list of similar items"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Message"

  /query:
    get:
      tags:
      - "query todo"
      summary: "todo"
      description: "todo"
      operationId: "query"
      produces:
      - "application/json"
      parameters:
      - name: "string"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pet"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      security:
      - api_key: []
definitions:
  Message:
    type: "object"
    properties:
      message:
        type: "string"
