# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ForexSymbol(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'display_symbol': 'str',
        'symbol': 'str'
    }

    attribute_map = {
        'description': 'description',
        'display_symbol': 'displaySymbol',
        'symbol': 'symbol'
    }

    def __init__(self, description=None, display_symbol=None, symbol=None, _configuration=None):  # noqa: E501
        """ForexSymbol - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._display_symbol = None
        self._symbol = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if display_symbol is not None:
            self.display_symbol = display_symbol
        if symbol is not None:
            self.symbol = symbol

    @property
    def description(self):
        """Gets the description of this ForexSymbol.  # noqa: E501

        Symbol description  # noqa: E501

        :return: The description of this ForexSymbol.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ForexSymbol.

        Symbol description  # noqa: E501

        :param description: The description of this ForexSymbol.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def display_symbol(self):
        """Gets the display_symbol of this ForexSymbol.  # noqa: E501

        Display symbol name.  # noqa: E501

        :return: The display_symbol of this ForexSymbol.  # noqa: E501
        :rtype: str
        """
        return self._display_symbol

    @display_symbol.setter
    def display_symbol(self, display_symbol):
        """Sets the display_symbol of this ForexSymbol.

        Display symbol name.  # noqa: E501

        :param display_symbol: The display_symbol of this ForexSymbol.  # noqa: E501
        :type: str
        """

        self._display_symbol = display_symbol

    @property
    def symbol(self):
        """Gets the symbol of this ForexSymbol.  # noqa: E501

        Unique symbol used to identify this symbol used in <code>/forex/candle</code> endpoint.  # noqa: E501

        :return: The symbol of this ForexSymbol.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this ForexSymbol.

        Unique symbol used to identify this symbol used in <code>/forex/candle</code> endpoint.  # noqa: E501

        :param symbol: The symbol of this ForexSymbol.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForexSymbol, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForexSymbol):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ForexSymbol):
            return True

        return self.to_dict() != other.to_dict()
