# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IndexHistoricalConstituent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'symbol': 'str',
        'action': 'str',
        '_date': 'date'
    }

    attribute_map = {
        'symbol': 'symbol',
        'action': 'action',
        '_date': 'date'
    }

    def __init__(self, symbol=None, action=None, _date=None, _configuration=None):  # noqa: E501
        """IndexHistoricalConstituent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._symbol = None
        self._action = None
        self.__date = None
        self.discriminator = None

        if symbol is not None:
            self.symbol = symbol
        if action is not None:
            self.action = action
        if _date is not None:
            self._date = _date

    @property
    def symbol(self):
        """Gets the symbol of this IndexHistoricalConstituent.  # noqa: E501

        Symbol  # noqa: E501

        :return: The symbol of this IndexHistoricalConstituent.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this IndexHistoricalConstituent.

        Symbol  # noqa: E501

        :param symbol: The symbol of this IndexHistoricalConstituent.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def action(self):
        """Gets the action of this IndexHistoricalConstituent.  # noqa: E501

        <code>add</code> or <code>remove</code>.  # noqa: E501

        :return: The action of this IndexHistoricalConstituent.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this IndexHistoricalConstituent.

        <code>add</code> or <code>remove</code>.  # noqa: E501

        :param action: The action of this IndexHistoricalConstituent.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def _date(self):
        """Gets the _date of this IndexHistoricalConstituent.  # noqa: E501

        Date of joining or leaving the index.  # noqa: E501

        :return: The _date of this IndexHistoricalConstituent.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this IndexHistoricalConstituent.

        Date of joining or leaving the index.  # noqa: E501

        :param _date: The _date of this IndexHistoricalConstituent.  # noqa: E501
        :type: date
        """

        self.__date = _date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndexHistoricalConstituent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndexHistoricalConstituent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IndexHistoricalConstituent):
            return True

        return self.to_dict() != other.to_dict()
