# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MarketNews(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        '_datetime': 'int',
        'headline': 'str',
        'id': 'int',
        'image': 'str',
        'related': 'str',
        'source': 'str',
        'summary': 'str',
        'url': 'str'
    }

    attribute_map = {
        'category': 'category',
        '_datetime': 'datetime',
        'headline': 'headline',
        'id': 'id',
        'image': 'image',
        'related': 'related',
        'source': 'source',
        'summary': 'summary',
        'url': 'url'
    }

    def __init__(self, category=None, _datetime=None, headline=None, id=None, image=None, related=None, source=None, summary=None, url=None, _configuration=None):  # noqa: E501
        """MarketNews - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._category = None
        self.__datetime = None
        self._headline = None
        self._id = None
        self._image = None
        self._related = None
        self._source = None
        self._summary = None
        self._url = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if _datetime is not None:
            self._datetime = _datetime
        if headline is not None:
            self.headline = headline
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if related is not None:
            self.related = related
        if source is not None:
            self.source = source
        if summary is not None:
            self.summary = summary
        if url is not None:
            self.url = url

    @property
    def category(self):
        """Gets the category of this MarketNews.  # noqa: E501

        News category.  # noqa: E501

        :return: The category of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this MarketNews.

        News category.  # noqa: E501

        :param category: The category of this MarketNews.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def _datetime(self):
        """Gets the _datetime of this MarketNews.  # noqa: E501

        Published time in UNIX timestamp.  # noqa: E501

        :return: The _datetime of this MarketNews.  # noqa: E501
        :rtype: int
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime):
        """Sets the _datetime of this MarketNews.

        Published time in UNIX timestamp.  # noqa: E501

        :param _datetime: The _datetime of this MarketNews.  # noqa: E501
        :type: int
        """

        self.__datetime = _datetime

    @property
    def headline(self):
        """Gets the headline of this MarketNews.  # noqa: E501

        News headline.  # noqa: E501

        :return: The headline of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._headline

    @headline.setter
    def headline(self, headline):
        """Sets the headline of this MarketNews.

        News headline.  # noqa: E501

        :param headline: The headline of this MarketNews.  # noqa: E501
        :type: str
        """

        self._headline = headline

    @property
    def id(self):
        """Gets the id of this MarketNews.  # noqa: E501

        News ID. This value can be used for <code>minId</code> params to get the latest news only.  # noqa: E501

        :return: The id of this MarketNews.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MarketNews.

        News ID. This value can be used for <code>minId</code> params to get the latest news only.  # noqa: E501

        :param id: The id of this MarketNews.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this MarketNews.  # noqa: E501

        Thumbnail image URL.  # noqa: E501

        :return: The image of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this MarketNews.

        Thumbnail image URL.  # noqa: E501

        :param image: The image of this MarketNews.  # noqa: E501
        :type: str
        """

        self._image = image

    @property
    def related(self):
        """Gets the related of this MarketNews.  # noqa: E501

        Related stocks and companies mentioned in the article.  # noqa: E501

        :return: The related of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._related

    @related.setter
    def related(self, related):
        """Sets the related of this MarketNews.

        Related stocks and companies mentioned in the article.  # noqa: E501

        :param related: The related of this MarketNews.  # noqa: E501
        :type: str
        """

        self._related = related

    @property
    def source(self):
        """Gets the source of this MarketNews.  # noqa: E501

        News source.  # noqa: E501

        :return: The source of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this MarketNews.

        News source.  # noqa: E501

        :param source: The source of this MarketNews.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def summary(self):
        """Gets the summary of this MarketNews.  # noqa: E501

        News summary.  # noqa: E501

        :return: The summary of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this MarketNews.

        News summary.  # noqa: E501

        :param summary: The summary of this MarketNews.  # noqa: E501
        :type: str
        """

        self._summary = summary

    @property
    def url(self):
        """Gets the url of this MarketNews.  # noqa: E501

        URL of the original article.  # noqa: E501

        :return: The url of this MarketNews.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this MarketNews.

        URL of the original article.  # noqa: E501

        :param url: The url of this MarketNews.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarketNews, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarketNews):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MarketNews):
            return True

        return self.to_dict() != other.to_dict()
