# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Sentiment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bearish_percent': 'float',
        'bullish_percent': 'float'
    }

    attribute_map = {
        'bearish_percent': 'bearishPercent',
        'bullish_percent': 'bullishPercent'
    }

    def __init__(self, bearish_percent=None, bullish_percent=None, _configuration=None):  # noqa: E501
        """Sentiment - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bearish_percent = None
        self._bullish_percent = None
        self.discriminator = None

        if bearish_percent is not None:
            self.bearish_percent = bearish_percent
        if bullish_percent is not None:
            self.bullish_percent = bullish_percent

    @property
    def bearish_percent(self):
        """Gets the bearish_percent of this Sentiment.  # noqa: E501

          # noqa: E501

        :return: The bearish_percent of this Sentiment.  # noqa: E501
        :rtype: float
        """
        return self._bearish_percent

    @bearish_percent.setter
    def bearish_percent(self, bearish_percent):
        """Sets the bearish_percent of this Sentiment.

          # noqa: E501

        :param bearish_percent: The bearish_percent of this Sentiment.  # noqa: E501
        :type: float
        """

        self._bearish_percent = bearish_percent

    @property
    def bullish_percent(self):
        """Gets the bullish_percent of this Sentiment.  # noqa: E501

          # noqa: E501

        :return: The bullish_percent of this Sentiment.  # noqa: E501
        :rtype: float
        """
        return self._bullish_percent

    @bullish_percent.setter
    def bullish_percent(self, bullish_percent):
        """Sets the bullish_percent of this Sentiment.

          # noqa: E501

        :param bullish_percent: The bullish_percent of this Sentiment.  # noqa: E501
        :type: float
        """

        self._bullish_percent = bullish_percent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Sentiment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sentiment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Sentiment):
            return True

        return self.to_dict() != other.to_dict()
