# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SocialSentiment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'symbol': 'str',
        'reddit': 'list[RedditSentimentContent]',
        'twitter': 'list[TwitterSentimentContent]'
    }

    attribute_map = {
        'symbol': 'symbol',
        'reddit': 'reddit',
        'twitter': 'twitter'
    }

    def __init__(self, symbol=None, reddit=None, twitter=None, _configuration=None):  # noqa: E501
        """SocialSentiment - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._symbol = None
        self._reddit = None
        self._twitter = None
        self.discriminator = None

        if symbol is not None:
            self.symbol = symbol
        if reddit is not None:
            self.reddit = reddit
        if twitter is not None:
            self.twitter = twitter

    @property
    def symbol(self):
        """Gets the symbol of this SocialSentiment.  # noqa: E501

        Company symbol.  # noqa: E501

        :return: The symbol of this SocialSentiment.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this SocialSentiment.

        Company symbol.  # noqa: E501

        :param symbol: The symbol of this SocialSentiment.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def reddit(self):
        """Gets the reddit of this SocialSentiment.  # noqa: E501

        Reddit sentiment.  # noqa: E501

        :return: The reddit of this SocialSentiment.  # noqa: E501
        :rtype: list[RedditSentimentContent]
        """
        return self._reddit

    @reddit.setter
    def reddit(self, reddit):
        """Sets the reddit of this SocialSentiment.

        Reddit sentiment.  # noqa: E501

        :param reddit: The reddit of this SocialSentiment.  # noqa: E501
        :type: list[RedditSentimentContent]
        """

        self._reddit = reddit

    @property
    def twitter(self):
        """Gets the twitter of this SocialSentiment.  # noqa: E501

        Twitter sentiment.  # noqa: E501

        :return: The twitter of this SocialSentiment.  # noqa: E501
        :rtype: list[TwitterSentimentContent]
        """
        return self._twitter

    @twitter.setter
    def twitter(self, twitter):
        """Sets the twitter of this SocialSentiment.

        Twitter sentiment.  # noqa: E501

        :param twitter: The twitter of this SocialSentiment.  # noqa: E501
        :type: list[TwitterSentimentContent]
        """

        self._twitter = twitter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SocialSentiment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SocialSentiment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SocialSentiment):
            return True

        return self.to_dict() != other.to_dict()
