# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Transactions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'share': 'int',
        'change': 'int',
        'filing_date': 'date',
        'transaction_date': 'date',
        'transaction_price': 'float',
        'transaction_code': 'str'
    }

    attribute_map = {
        'name': 'name',
        'share': 'share',
        'change': 'change',
        'filing_date': 'filingDate',
        'transaction_date': 'transactionDate',
        'transaction_price': 'transactionPrice',
        'transaction_code': 'transactionCode'
    }

    def __init__(self, name=None, share=None, change=None, filing_date=None, transaction_date=None, transaction_price=None, transaction_code=None, _configuration=None):  # noqa: E501
        """Transactions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._share = None
        self._change = None
        self._filing_date = None
        self._transaction_date = None
        self._transaction_price = None
        self._transaction_code = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if share is not None:
            self.share = share
        if change is not None:
            self.change = change
        if filing_date is not None:
            self.filing_date = filing_date
        if transaction_date is not None:
            self.transaction_date = transaction_date
        if transaction_price is not None:
            self.transaction_price = transaction_price
        if transaction_code is not None:
            self.transaction_code = transaction_code

    @property
    def name(self):
        """Gets the name of this Transactions.  # noqa: E501

        Insider's name.  # noqa: E501

        :return: The name of this Transactions.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Transactions.

        Insider's name.  # noqa: E501

        :param name: The name of this Transactions.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def share(self):
        """Gets the share of this Transactions.  # noqa: E501

        Number of shares held after the transaction.  # noqa: E501

        :return: The share of this Transactions.  # noqa: E501
        :rtype: int
        """
        return self._share

    @share.setter
    def share(self, share):
        """Sets the share of this Transactions.

        Number of shares held after the transaction.  # noqa: E501

        :param share: The share of this Transactions.  # noqa: E501
        :type: int
        """

        self._share = share

    @property
    def change(self):
        """Gets the change of this Transactions.  # noqa: E501

        Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction.  # noqa: E501

        :return: The change of this Transactions.  # noqa: E501
        :rtype: int
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this Transactions.

        Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction.  # noqa: E501

        :param change: The change of this Transactions.  # noqa: E501
        :type: int
        """

        self._change = change

    @property
    def filing_date(self):
        """Gets the filing_date of this Transactions.  # noqa: E501

        Filing date.  # noqa: E501

        :return: The filing_date of this Transactions.  # noqa: E501
        :rtype: date
        """
        return self._filing_date

    @filing_date.setter
    def filing_date(self, filing_date):
        """Sets the filing_date of this Transactions.

        Filing date.  # noqa: E501

        :param filing_date: The filing_date of this Transactions.  # noqa: E501
        :type: date
        """

        self._filing_date = filing_date

    @property
    def transaction_date(self):
        """Gets the transaction_date of this Transactions.  # noqa: E501

        Transaction date.  # noqa: E501

        :return: The transaction_date of this Transactions.  # noqa: E501
        :rtype: date
        """
        return self._transaction_date

    @transaction_date.setter
    def transaction_date(self, transaction_date):
        """Sets the transaction_date of this Transactions.

        Transaction date.  # noqa: E501

        :param transaction_date: The transaction_date of this Transactions.  # noqa: E501
        :type: date
        """

        self._transaction_date = transaction_date

    @property
    def transaction_price(self):
        """Gets the transaction_price of this Transactions.  # noqa: E501

        Average transaction price.  # noqa: E501

        :return: The transaction_price of this Transactions.  # noqa: E501
        :rtype: float
        """
        return self._transaction_price

    @transaction_price.setter
    def transaction_price(self, transaction_price):
        """Sets the transaction_price of this Transactions.

        Average transaction price.  # noqa: E501

        :param transaction_price: The transaction_price of this Transactions.  # noqa: E501
        :type: float
        """

        self._transaction_price = transaction_price

    @property
    def transaction_code(self):
        """Gets the transaction_code of this Transactions.  # noqa: E501

        Transaction code. A list of codes and their meanings can be found <a href=\"https://www.sec.gov/about/forms/form4data.pdf\" target=\"_blank\" rel=\"noopener\">here</a>.  # noqa: E501

        :return: The transaction_code of this Transactions.  # noqa: E501
        :rtype: str
        """
        return self._transaction_code

    @transaction_code.setter
    def transaction_code(self, transaction_code):
        """Sets the transaction_code of this Transactions.

        Transaction code. A list of codes and their meanings can be found <a href=\"https://www.sec.gov/about/forms/form4data.pdf\" target=\"_blank\" rel=\"noopener\">here</a>.  # noqa: E501

        :param transaction_code: The transaction_code of this Transactions.  # noqa: E501
        :type: str
        """

        self._transaction_code = transaction_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Transactions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Transactions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Transactions):
            return True

        return self.to_dict() != other.to_dict()
