# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TranscriptContent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'speech': 'list[str]',
        'session': 'str'
    }

    attribute_map = {
        'name': 'name',
        'speech': 'speech',
        'session': 'session'
    }

    def __init__(self, name=None, speech=None, session=None, _configuration=None):  # noqa: E501
        """TranscriptContent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._speech = None
        self._session = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if speech is not None:
            self.speech = speech
        if session is not None:
            self.session = session

    @property
    def name(self):
        """Gets the name of this TranscriptContent.  # noqa: E501

        Speaker's name  # noqa: E501

        :return: The name of this TranscriptContent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TranscriptContent.

        Speaker's name  # noqa: E501

        :param name: The name of this TranscriptContent.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def speech(self):
        """Gets the speech of this TranscriptContent.  # noqa: E501

        Speaker's speech  # noqa: E501

        :return: The speech of this TranscriptContent.  # noqa: E501
        :rtype: list[str]
        """
        return self._speech

    @speech.setter
    def speech(self, speech):
        """Sets the speech of this TranscriptContent.

        Speaker's speech  # noqa: E501

        :param speech: The speech of this TranscriptContent.  # noqa: E501
        :type: list[str]
        """

        self._speech = speech

    @property
    def session(self):
        """Gets the session of this TranscriptContent.  # noqa: E501

        Earnings calls section (management discussion or Q&A)  # noqa: E501

        :return: The session of this TranscriptContent.  # noqa: E501
        :rtype: str
        """
        return self._session

    @session.setter
    def session(self, session):
        """Sets the session of this TranscriptContent.

        Earnings calls section (management discussion or Q&A)  # noqa: E501

        :param session: The session of this TranscriptContent.  # noqa: E501
        :type: str
        """

        self._session = session

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranscriptContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranscriptContent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranscriptContent):
            return True

        return self.to_dict() != other.to_dict()
